image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787:TnGEOx35GXMhyKLjDGz9Aw==
    - kevinglasson.cornflakes-linter@0.5.1:KAaMshgHOKan8eojXQ53OQ==
    - zignd.html-css-class-completion@1.20.0:tM/3cqwniwGGWk/oMEaO6Q==
    - janne252.fontawesome-autocomplete@1.1.2:7HhKTj8hxobEat1XAUsNtg==
    - idleberg.badges@1.0.11:cIc1yBExRVxwDtCFOfgC9w==
    - formulahendry.auto-close-tag@0.5.10:GSIjAJo5b8OeW5FdWSDA8A==